name: DailyRewards
description: Offers daily/monthly/once rewards to users through a simple GUI.

version: 1.0
main: com.tek.rewards.main.Main

commands:
  rewards:
    description: Opens the rewards menu.
    aliases: [dailyrewards]